// import * as Ai from "react-scripts/ai";
// import * as Bi from "react-scripts/bi";
// import * as Ri from "react-scripts/ri";
// import * as Gi from "react-scripts/gi";
// import * as Fa from "react-scripts/fa";
// import * as Bs from "react-icons/bs";

const categories = [
  {
    _id: 1,
    name: "Mobile",
    icon: "images/suggest/automobile.png",
    numberOfAds: 21211,
    link: "/ads/mobile",
    subcategory: [
      {
        _id: 1,
        icon: "images/suggest/automobile.png",
        title: "Mobile Phone",
        ads: 21211,
        link: "/ads/mobile/phone",
      },
      {
        _id: 2,
        icon: "images/suggest/automobile.png",
        title: "Accessories",
        ads: 21211,
        link: "/ads/mobile/accessories",
      },
      {
        _id: 3,
        icon: "images/suggest/automobile.png",
        title: "Sim card",
        ads: 21211,
        link: "/ads/mobile/sim",
      },
      {
        _id: 4,
        icon: "images/suggest/automobile.png",
        title: "Wireless",
        ads: 21211,
        link: "/ads/mobile/wireless",
      },
    ],
  },
  {
    _id: 2,
    name: "Electronics",
    icon: "images/suggest/furniture.png",
    numberOfAds: 21211,
    link: "/ads/electronics",
    subcategory: [
      {
        _id: 1,
        icon: "",
        title: "laptop",
        ads: 21211,
        link: "/ads/electronics/laptop",
      },
      {
        _id: 2,
        icon: "images/suggest/furniture.png",
        title: "dektop",
        ads: 21211,
        link: "/ads/electronics/desktop",
      },
      {
        _id: 3,
        icon: "images/suggest/furniture.png",
        title: "Accessories",
        ads: 21211,
        link: "/ads/electronics/accessories",
      },
      {
        _id: 4,
        icon: "images/suggest/furniture.png",
        title: "Camera",
        ads: 21211,
        link: "/ads/electronics/camera",
      },
    ],
  },
  {
    _id: 3,
    name: "Home & Livings",
    icon: "images/suggest/properties.png",
    numberOfAds: 21211,
    link: "/ads/home",
    subcategory: [
      {
        _id: 1,
        icon: "images/suggest/properties.png",
        title: "Category 1 1",
        ads: 21211,
      },
      {
        _id: 2,
        icon: "images/suggest/properties.png",
        title: "Category 1 2",
        ads: 21211,
      },
      {
        _id: 3,
        icon: "images/suggest/properties.png",
        title: "Category 1 3",
        ads: 21211,
      },
      {
        _id: 4,
        icon: "images/suggest/properties.png",
        title: "Category 1 4",
        ads: 21211,
        link: "/ads/home",
      },
    ],
  },
  {
    _id: 4,
    name: "Vehicles",
    icon: "images/suggest/electronics.png",
    numberOfAds: 21211,
    link: "/ads/vehicles",
    subcategory: [
      {
        _id: 1,
        icon: "images/suggest/electronics.png",
        title: "Category 1 1",
        ads: 21211,
      },
      {
        _id: 2,
        icon: "images/suggest/electronics.png",
        title: "Category 1 2",
        ads: 21211,
      },
      {
        _id: 3,
        icon: "images/suggest/electronics.png",
        title: "Category 1 3",
        ads: 21211,
      },
      {
        _id: 4,
        icon: "",
        title: "Category 1 4",
        ads: 21211,
        link: "/ads/vehicles",
      },
    ],
  },
  {
    _id: 5,
    name: "Property",
    icon: "images/suggest/hospitality.png",
    numberOfAds: 21211,
    link: "/ads/property",
    subcategory: [
      {
        _id: 1,
        icon: "images/suggest/hospitality.png",
        title: "Category 1 1",
        ads: 21211,
      },
      {
        _id: 2,
        icon: "images/suggest/hospitality.png",
        title: "Category 1 2",
        ads: 21211,
      },
      {
        _id: 3,
        icon: "images/suggest/hospitality.png",
        title: "Category 1 3",
        ads: 21211,
      },
      {
        _id: 4,
        icon: "images/suggest/hospitality.png",
        title: "Category 1 4",
        ads: 21211,
        link: "/ads/property",
      },
    ],
  },
  {
    _id: 6,
    name: "Pet & Animale",
    icon: "images/suggest/gadgets.png",
    numberOfAds: 21211,
    link: "/ads/pet",
    subcategory: [
      {
        _id: 1,
        icon: "images/suggest/food.png",
        title: "Category 1 1",
        ads: 21211,
      },
      {
        _id: 2,
        icon: "images/suggest/food.png",
        title: "Category 1 2",
        ads: 21211,
      },
      {
        _id: 3,
        icon: "images/suggest/food.png",
        title: "Category 1 3",
        ads: 21211,
      },
      {
        _id: 4,
        icon: "images/suggest/food.png",
        title: "Category 1 4",
        ads: 21211,
        link: "/ads/pet",
      },
    ],
  },
  {
    _id: 7,
    name: "Fashion & Beauty",
    icon: "images/suggest/education.png",
    numberOfAds: 21211,
    link: "/ads/fashion",
    subcategory: [
      {
        _id: 1,
        icon: "images/suggest/education.png",
        title: "Category 1 1",
        ads: 21211,
      },
      {
        _id: 2,
        icon: "images/suggest/education.png",
        title: "Category 1 2",
        ads: 21211,
      },
      {
        _id: 3,
        icon: "images/suggest/education.png",
        title: "Category 1 3",
        ads: 21211,
      },
      {
        _id: 4,
        icon: "images/suggest/education.png",
        title: "Category 1 4",
        ads: 21211,
      },
      {
        _id: 5,
        icon: "images/suggest/education.png",
        title: "Category 1 3",
        ads: 21211,
      },
      {
        _id: 6,
        icon: "images/suggest/education.png",
        title: "Category 1 4",
        ads: 21211,
      },
      {
        _id: 7,
        icon: "images/suggest/education.png",
        title: "Category 1 3",
        ads: 21211,
      },
      {
        _id: 8,
        icon: "images/suggest/education.png",
        title: "Category 1 4",
        ads: 21211,
        link: "/ads/fashion",
      },
    ],
  },
  {
    _id: 14,
    name: "Hobbies, Sports & Kids",
    icon: "images/suggest/software.png",
    numberOfAds: 21211,
    link: "/ads/hobbies",
    subcategory: [
      {
        _id: 1,
        icon: "images/suggest/software.png",
        title: "Category 1 1",
        ads: 21211,
      },
      {
        _id: 2,
        icon: "images/suggest/software.png",
        title: "Category 1 2",
        ads: 21211,
      },
      {
        _id: 3,
        icon: "images/suggest/software.png",
        title: "Category 1 3",
        ads: 21211,
      },
      {
        _id: 4,
        icon: "images/suggest/software.png",
        title: "Category 1 4",
        ads: 21211,
        link: "/ads/hobbies",
      },
    ],
  },
  {
    _id: 8,
    name: "Industry & Business",
    icon: "images/suggest/food.png",
    numberOfAds: 21211,
    link: "/ads/industry",
    subcategory: [
      {
        _id: 1,
        icon: "images/suggest/food.png",
        title: "Category 1 1",
        ads: 21211,
      },
      {
        _id: 2,
        icon: "images/suggest/food.png",
        title: "Category 1 2",
        ads: 21211,
      },
      {
        _id: 3,
        icon: "images/suggest/food.png",
        title: "Category 1 3",
        ads: 21211,
      },
      {
        _id: 4,
        icon: "images/suggest/food.png",
        title: "Category 1 4",
        ads: 21211,
        link: "/ads/industry",
      },
    ],
  },
  {
    _id: 15,
    name: "Education",
    icon: "images/suggest/animals.png",
    numberOfAds: 21211,
    link: "/ads/education",
    subcategory: [
      {
        _id: 1,
        icon: "images/suggest/animals.png",
        title: "Category 1 1",
        ads: 21211,
        link: "/ads/education",
      },
      {
        _id: 2,
        icon: "images/suggest/animals.png",
        title: "Category 1 2",
        ads: 21211,
        link: "/ads/education",
      },
      {
        _id: 3,
        icon: "images/suggest/animals.png",
        title: "Category 1 3",
        ads: 21211,
        link: "/ads/education",
      },
      {
        _id: 4,
        icon: "images/suggest/animals.png",
        title: "Category 1 4",
        ads: 21211,
        link: "/ads/education",
      },
    ],
  },
];
export default categories;
