export const products = [
  // status : booking, sale, rental
  {
    _id: 1,
    img: "images/product/01.jpg",
    views: 100,
    rating: 4.5,
    status: "booking",
    isWishList: false,
    category: "mobile",
    subcategory: "",
    price: 1210,
    location: "Uttara, Dhaka",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati numquam debitis in sequi.",
    time: "40",
  },
  {
    _id: 2,
    img: "images/product/02.jpg",
    views: 100,
    rating: 4.5,
    status: "booking",
    isWishList: false,
    category: "mobile",
    subcategory: "",
    price: 1210,
    location: "Uttara, Dhaka",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati numquam debitis in sequi.",
    time: "40",
  },
  {
    _id: 3,
    img: "images/product/03.jpg",
    views: 100,
    rating: 4.5,
    status: "booking",
    isWishList: false,
    category: "mobile",
    subcategory: "",
    price: 1210,
    location: "Uttara, Dhaka",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati numquam debitis in sequi.",
    time: "40",
  },
  {
    _id: 4,
    img: "images/product/04.jpg",

    views: 100,
    rating: 4.5,
    status: "booking",
    isWishList: false,
    category: "mobile",
    subcategory: "",
    price: 1210,
    location: "Uttara, Dhaka",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati numquam debitis in sequi.",
    time: "40",
  },
  {
    _id: 5,
    img: "images/product/05.jpg",

    views: 100,
    rating: 4.5,
    status: "booking",
    isWishList: false,
    category: "mobile",
    subcategory: "",
    price: 1210,
    location: "Uttara, Dhaka",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati numquam debitis in sequi.",
    time: "40",
  },
  {
    _id: 6,
    img: "images/product/06.jpg",

    views: 100,
    rating: 4.5,
    status: "booking",
    isWishList: false,
    category: "mobile",
    subcategory: "",
    price: 1210,
    location: "Uttara, Dhaka",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati numquam debitis in sequi.",
    time: "40",
  },
  {
    _id: 7,
    img: "images/product/01.jpg",
  },
  {
    _id: 8,
    img: "images/product/02.jpg",

    views: 100,
    rating: 4.5,
    status: "booking",
    isWishList: false,
    category: "mobile",
    subcategory: "",
    price: 1210,
    location: "Uttara, Dhaka",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati numquam debitis in sequi.",
    time: "40",
  },
  {
    _id: 9,
    img: "images/product/03.jpg",
    views: 100,
    rating: 4.5,
    status: "booking",
    isWishList: false,
    category: "mobile",
    subcategory: "",
    price: 1210,
    location: "Uttara, Dhaka",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati numquam debitis in sequi.",
    time: "40",
  },
  {
    _id: 10,
    img: "images/product/04.jpg",
    views: 100,
    rating: 4.5,
    status: "booking",
    isWishList: false,
    category: "mobile",
    subcategory: "",
    price: 1210,
    location: "Uttara, Dhaka",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati numquam debitis in sequi.",
    time: "40",
  },
  {
    _id: 11,
    img: "images/product/05.jpg",
    views: 100,
    rating: 4.5,
    status: "booking",
    isWishList: false,
    category: "mobile",
    subcategory: "",
    price: 1210,
    location: "Uttara, Dhaka",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati numquam debitis in sequi.",
    time: "40",
  },
  {
    _id: 12,
    img: "images/product/06.jpg",
    views: 100,
    rating: 4.5,
    status: "booking",
    isWishList: false,
    category: "mobile",
    subcategory: "",
    price: 1210,
    location: "Uttara, Dhaka",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati numquam debitis in sequi.",
    time: "40",
  },
  {
    _id: 13,
    img: "images/product/05.jpg",
    views: 100,
    rating: 4.5,
    status: "booking",
    isWishList: false,
    category: "mobile",
    subcategory: "",
    price: 1210,
    location: "Uttara, Dhaka",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati numquam debitis in sequi.",
    time: "40",
  },
  {
    _id: 14,
    img: "images/product/06.jpg",
    views: 100,
    rating: 4.5,
    status: "booking",
    isWishList: false,
    category: "mobile",
    subcategory: "",
    price: 1210,
    location: "Uttara, Dhaka",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati numquam debitis in sequi.",
    time: "40",
  },
  {
    _id: 15,
    img: "images/product/05.jpg",
    views: 100,
    rating: 4.5,
    status: "booking",
    isWishList: false,
    category: "mobile",
    subcategory: "",
    price: 1210,
    location: "Uttara, Dhaka",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati numquam debitis in sequi.",
    time: "40",
  },
  {
    _id: 16,
    img: "images/product/06.jpg",
    views: 100,
    rating: 4.5,
    status: "booking",
    isWishList: false,
    category: "mobile",
    subcategory: "",
    price: 1210,
    location: "Uttara, Dhaka",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati numquam debitis in sequi.",
    time: "40",
  },
];
