export const productService = [
  // status : booking, sale, rental
  //price type : free, featured, spotlight
  {
    _id: 1,
    img: "images/product/01.jpg",
    views: 100,
    rating: 4.5,
    status: "booking",
    isWishList: false,
    category: "mobile",
    subcategory: "phone",
    price: 9,
    location: "Uttara, Dhaka",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati numquam debitis in sequi.",
    time: "40",
    priceType: "spotlight",
    locationArea: { location: "Dhaka", city: "Banani" },
  },
  {
    _id: 2,
    img: "images/product/02.jpg",
    views: 100,
    rating: 4.5,
    status: "booking",
    isWishList: false,
    category: "electronics",
    subcategory: "laptop",
    price: 20,
    location: "Uttara, Dhaka",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati numquam debitis in sequi.",
    time: "40",
    priceType: "free",
    locationArea: { location: "Dhaka", city: "Dhanmandi" },
  },
  {
    _id: 3,
    img: "images/product/03.jpg",
    views: 100,
    rating: 4.5,
    status: "booking",
    isWishList: false,
    category: "mobile",
    subcategory: "sim",
    price: 299,
    location: "Uttara, Dhaka",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati numquam debitis in sequi.",
    time: "40",
    priceType: "featured",
    locationArea: { location: "Dhaka", city: "Banani" },
  },
  {
    _id: 4,
    img: "images/product/04.jpg",
    views: 100,
    rating: 4.5,
    status: "booking",
    isWishList: false,
    category: "electronics",
    subcategory: "desktop",
    price: 20,
    location: "Uttara, Dhaka",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati numquam debitis in sequi.",
    time: "40",
    priceType: "spotlight",
    locationArea: { location: "Dhaka", city: "Mohammadpur" },
  },
  {
    _id: 5,
    img: "images/product/05.jpg",
    views: 100,
    rating: 4.5,
    status: "booking",
    isWishList: false,
    category: "mobile",
    subcategory: "phone",
    price: 20,
    location: "Uttara, Dhaka",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati numquam debitis in sequi.",
    time: "40",
    priceType: "free",
    locationArea: { location: "Dhaka", city: "Banani" },
  },
  {
    _id: 6,
    img: "images/product/06.jpg",
    views: 100,
    rating: 4.5,
    status: "booking",
    isWishList: false,
    category: "electronics",
    subcategory: "laptop",
    price: 20,
    location: "Uttara, Dhaka",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati numquam debitis in sequi.",
    time: "40",
    package: "spotlight",
    priceType: "featured",
    locationArea: { location: "Dhaka", city: "Banani" },
  },
  {
    _id: 7,
    img: "images/product/01.jpg",
    views: 100,
    rating: 4.5,
    status: "sale",
    isWishList: false,
    category: "electronics",
    subcategory: "laptop",
    price: 20,
    location: "Uttara, Dhaka",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati numquam debitis in sequi.",
    time: "40",
    priceType: "spotlight",
    locationArea: { location: "Dhaka", city: "Mohammadpur" },
  },
  {
    _id: 8,
    img: "images/product/02.jpg",
    views: 100,
    rating: 4.5,
    status: "rental",
    isWishList: false,
    category: "mobile",
    subcategory: "sim",
    price: 20,
    location: "Uttara, Dhaka",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati numquam debitis in sequi.",
    time: "40",
    priceType: "featured",
    locationArea: { location: "Dhaka", city: "Banani" },
  },
  {
    _id: 9,
    img: "images/product/03.jpg",
    views: 100,
    rating: 4.5,
    status: "booking",
    isWishList: false,
    category: "electronics",
    subcategory: "desktop",
    price: 20,
    location: "Uttara, Dhaka",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati numquam debitis in sequi.",
    time: "40",
    priceType: "spotlight",
    locationArea: { location: "Dhaka", city: "Dhanmondi" },
  },
  {
    _id: 10,
    img: "images/product/04.jpg",
    views: 100,
    rating: 4.5,
    status: "sale",
    isWishList: false,
    category: "mobile",
    subcategory: "phone",
    price: 20,
    location: "Uttara, Dhaka",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati numquam debitis in sequi.",
    time: "40",
    priceType: "free",
  },
  {
    _id: 11,
    img: "images/product/05.jpg",
    views: 100,
    rating: 4.5,
    status: "rental",
    isWishList: false,
    category: "electronics",
    subcategory: "laptop",
    price: 20,
    location: "Uttara, Dhaka",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati numquam debitis in sequi.",
    time: "40",
    priceType: "free",
    locationArea: { location: "Rangpur", city: "Dinajpur" },
  },
  {
    _id: 12,
    img: "images/product/06.jpg",
    views: 100,
    rating: 4.5,
    status: "booking",
    isWishList: false,
    category: "mobile",
    subcategory: "sim",
    price: 20,
    location: "Uttara, Dhaka",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati numquam debitis in sequi.",
    time: "40",
    priceType: "featured",
    locationArea: { location: "Rangpur", city: "Dinajpur" },
  },
  {
    _id: 13,
    img: "images/product/05.jpg",
    views: 100,
    rating: 4.5,
    status: "sale",
    isWishList: false,
    category: "electronics",
    subcategory: "desktop",
    price: 20,
    location: "Uttara, Dhaka",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati numquam debitis in sequi.",
    time: "40",
    priceType: "free",
    locationArea: { location: "Chittagong", city: "Rangamati" },
  },
  {
    _id: 14,
    img: "images/product/06.jpg",
    views: 100,
    rating: 4.5,
    status: "rental",
    isWishList: false,
    category: "mobile",
    subcategory: "phone",
    price: 20,
    location: "Uttara, Dhaka",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati numquam debitis in sequi.",
    time: "40",
    priceType: "spotlight",
    locationArea: { location: "Chittagong", city: "Rangamati" },
  },
  {
    _id: 15,
    img: "images/product/05.jpg",
    views: 100,
    rating: 4.5,
    status: "booking",
    isWishList: false,
    category: "electronics",
    subcategory: "desktop",
    price: 20,
    location: "Uttara, Dhaka",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati numquam debitis in sequi.",
    time: "40",
    priceType: "featured",
    locationArea: { location: "Chittagong", city: "Khagrachari" },
  },
  {
    _id: 16,
    img: "images/product/06.jpg",
    views: 100,
    rating: 4.5,
    status: "sale",
    isWishList: false,
    category: "mobile",
    subcategory: "sim",
    price: 20,
    location: "Uttara, Dhaka",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati numquam debitis in sequi.",
    time: "40",
    priceType: "free",
    locationArea: { location: "Chittagong", city: "Khagrachari" },
  },
];
